version: '2'
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    links:
      - mysql_master
      - mysql_slave
    ports:
      - "8000:80"
      - "8443:443"
      - "10022:22"
    volumes:
      - ./app/:/app/
      - ./:/docker/
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - etc/environment.yml
      - etc/environment.development.yml
    environment:
      - VIRTUAL_HOST=.app.boilerplate.docker
      - VIRTUAL_PORT=80
      - POSTFIX_RELAYHOST=[mail]:1025


  #######################################
  # MySQL server
  #######################################
  mysql_master:
    build:
      context: docker/mysql/
  #     #dockerfile: MySQL-5.5.Dockerfile
      dockerfile: MySQL-5.6.Dockerfile
      # dockerfile: MySQL-5.7.Dockerfile
  #     #dockerfile: MariaDB-5.5.Dockerfile
  #     #dockerfile: MariaDB-10.Dockerfile
  #     #dockerfile: Percona-5.5.Dockerfile
  #     #dockerfile: Percona-5.6.Dockerfile
  #     #dockerfile: Percona-5.7.Dockerfile
    ports:
      - 13306:3306
    volumes:
      - mysql_master:/var/lib/mysql
    env_file:
      - etc/environment.yml
      - etc/environment.development.yml

  #######################################
  # MySQL server
  #######################################
  mysql_slave:
    links: 
      - mysql_master
    # image: tunganh/mysql:latest
    build:
      context: docker/mysql/
      #dockerfile: MySQL-5.5.Dockerfile
      # dockerfile: MySQL-5.6.Dockerfile
      dockerfile: MySQL-5.7.Dockerfile
      #dockerfile: MariaDB-5.5.Dockerfile
      #dockerfile: MariaDB-10.Dockerfile
      #dockerfile: Percona-5.5.Dockerfile
      #dockerfile: Percona-5.6.Dockerfile
      #dockerfile: Percona-5.7.Dockerfile
    ports:
      - 13307:3306
    volumes:
      - mysql_slave:/var/lib/mysql
    env_file:
      - etc/environment.yml
      - etc/environment.development.yml

  #######################################
  # phpMyAdmin
  #######################################
  phpmyadmin_master:
   image: phpmyadmin/phpmyadmin
   links:
     - mysql_master
   ports:
     - 8001:80
   environment:
     - PMA_HOSTS=mysql_master
     - VIRTUAL_HOST=pma.boilerplate.docker
     - VIRTUAL_PORT=80
   volumes:
     - phpmyadmin_master:/sessions

  #######################################
  # phpMyAdmin
  #######################################
  phpmyadmin_slave:
   image: phpmyadmin/phpmyadmin
   links:
     - mysql_slave
   ports:
     - 8002:80
   environment:
     - PMA_HOSTS=mysql_slave
     - VIRTUAL_HOST=pmasalve.boilerplate.docker
     - VIRTUAL_PORT=80
   volumes:
     - phpmyadmin_slave:/sessions


volumes:
  mysql_master:
  mysql_slave:
  phpmyadmin_master:
  phpmyadmin_slave:

